name = "torentchat-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-07-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[kv_namespaces]]
binding = "SIGNALING"
id = "5959fc8461264650aaa3cf26f58776ed"

[[kv_namespaces]]
binding = "PENDING"
id = "ddba4e87ea834f8cbaa23b662c4e9474"

[[kv_namespaces]]
binding = "PRESENCE"
id = "24a4202efd8d4d0baf2daf35cffcf881"
